### ISSUE TITLE
Cannot compile HELIOS-K - atomicMin/Max error

### ISSUE THREAD

**Issue by iancrossfield** [exoclime/HELIOS-K#7]
When I try to compile HELIOS-K by typing "make SM=30" at the command prompt, I get errors that seem to relate to the functions "atomicMin" and "atomicMax" (full output below).  Any suggestions would be welcome - many thanks.

> 
> 
> ianboxv2:~/Downloads/HELIOS-K-master> make SM=30
> nvcc -arch sm_30 --compiler-options -Wall -o heliosk heliosk.cu -DGIT_DESCRIBE=\""`git describe`"\" -DBUILD_DATE=\""`date`"\" -DBUILD_SYSTEM=\""`uname -a`"\" -DBUILD_PATH=\""`pwd`"\" -DBUILD_SM=\"30\"
> fatal: not a git repository (or any of the parent directories): .git
> voigt.h(1706): error: no instance of overloaded function "atomicMin" matches the argument list
>             argument types are: (long long *, long long)
> 
> voigt.h(1707): error: no instance of overloaded function "atomicMax" matches the argument list
>             argument types are: (long long *, long long)
> 
> 2 errors detected in the compilation of "/tmp/tmpxft_00007733_00000000-8_heliosk.cpp1.ii".
> Makefile:19: recipe for target 'heliosk' failed
> make: *** [heliosk] Error 1
>

**Comment by iancrossfield** [comment]
PS: Despite the message "fatal: not a git repository", the same atomicMin/Max errors occur whether I do a 'git clone' of the whole repo or just download the repo as a ZIP file.

**Comment by iancrossfield** [comment]
Further updates: this seems to be a known issue with CUDA for lower-powered GPUs (specifically, compute power < 3.5):
https://stackoverflow.com/questions/17399119/cant-we-use-atomic-operations-for-floating-point-variables-in-cuda
Although my GPU only has compute power = 3.0, I was able to compile HELIOS-K by just specifying "-sm=35".  Will update whether the code still successfully runs or not.

Regardless, might be worth updating the documentation to note this possible hiccup.

**Comment by sigrimm** [comment]
Hi,
thanks for letting me know about this issue. As you pointed out correctly the issue is because compute capability 3.0 does not support atomicMin and atomicMax for int64 types, as I use in Helios-k. 
From compute capability 3.5, these functions are supported, that why you could compile it with SM=35.

I will try to find a workaround without the atomicMin/Max functions. 

The 'not a git repository' message is not really important. In this ways you just don't get the used commit version and build date reported in the Info file.

**Comment by sigrimm** [comment]
I removed the atomic operations in Version 2.01 and the code should now compile and run with compute capability of 3.0.
